"""
Threshold evaluation and alert generation engine.
Monitors component health and generates alerts when thresholds are exceeded.
"""
from typing import Dict, List, Optional
from dataclasses import dataclass
from enum import Enum
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


class AlertLevel(str, Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class Alert:
    """Alert generated by threshold engine."""
    component_id: str
    level: AlertLevel
    metric_name: str
    current_value: float
    threshold_value: float
    timestamp: datetime
    message: str
    acknowledged: bool = False


class ThresholdEngine:
    """
    Evaluates component metrics against thresholds and manages alerts.
    Includes hysteresis to prevent alert flicker.
    """

    def __init__(self, hysteresis_percent: float = 10.0):
        """
        Initialize threshold engine.
        
        Args:
            hysteresis_percent: Hysteresis window as percentage of threshold
                              (prevents flicker when value oscillates around threshold)
        """
        self.hysteresis_percent = hysteresis_percent
        self.active_alerts: Dict[str, Alert] = {}  # component_id -> Alert
        self.alert_history: List[Alert] = []
        self.component_states: Dict[str, str] = {}  # Track current state per component

    def evaluate_metric(
        self,
        component_id: str,
        metric_name: str,
        current_value: float,
        threshold_warning: Optional[float],
        threshold_critical: Optional[float]
    ) -> Optional[Alert]:
        """
        Evaluate a metric against thresholds with hysteresis.
        
        Args:
            component_id: Component identifier
            metric_name: Name of the metric
            current_value: Current metric value
            threshold_warning: Warning threshold
            threshold_critical: Critical threshold
            
        Returns:
            Alert object if threshold exceeded, None otherwise
        """
        state_key = f"{component_id}:{metric_name}"
        current_state = self.component_states.get(state_key, "healthy")
        
        # Determine new state with hysteresis
        new_state = self._evaluate_with_hysteresis(
            current_value,
            current_state,
            threshold_warning,
            threshold_critical
        )
        
        self.component_states[state_key] = new_state
        
        # Generate alert if state changed to warning/critical
        if new_state in ["warning", "critical"] and current_state == "healthy":
            alert_level = AlertLevel.CRITICAL if new_state == "critical" else AlertLevel.WARNING
            threshold = threshold_critical if new_state == "critical" else threshold_warning
            
            alert = Alert(
                component_id=component_id,
                level=alert_level,
                metric_name=metric_name,
                current_value=current_value,
                threshold_value=threshold,
                timestamp=datetime.now(),
                message=self._generate_alert_message(
                    component_id,
                    metric_name,
                    current_value,
                    threshold,
                    alert_level
                )
            )
            
            self.active_alerts[component_id] = alert
            self.alert_history.append(alert)
            logger.warning(f"Alert generated: {alert.message}")
            return alert
        
        # Clear alert if state improved
        if new_state == "healthy" and current_state != "healthy":
            if component_id in self.active_alerts:
                logger.info(f"Alert cleared for {component_id}")
                del self.active_alerts[component_id]
        
        return None

    def _evaluate_with_hysteresis(
        self,
        value: float,
        current_state: str,
        threshold_warning: Optional[float],
        threshold_critical: Optional[float]
    ) -> str:
        """
        Evaluate state with hysteresis to prevent flicker.
        
        State transitions only occur when value crosses threshold by hysteresis window.
        
        Args:
            value: Current metric value
            current_state: Current state (healthy/warning/critical)
            threshold_warning: Warning threshold
            threshold_critical: Critical threshold
            
        Returns:
            New state (healthy/warning/critical)
        """
        # Calculate hysteresis margins
        warning_hyst = (threshold_warning * self.hysteresis_percent / 100) if threshold_warning else 0
        critical_hyst = (threshold_critical * self.hysteresis_percent / 100) if threshold_critical else 0
        
        if current_state == "critical":
            # Exit critical only if well below critical threshold
            if threshold_critical and value < (threshold_critical - critical_hyst):
                return "warning" if threshold_warning and value >= threshold_warning else "healthy"
            return "critical"
        
        elif current_state == "warning":
            # Exit warning only if well below warning threshold
            if threshold_warning and value < (threshold_warning - warning_hyst):
                return "healthy"
            # Enter critical if above critical threshold
            if threshold_critical and value >= threshold_critical:
                return "critical"
            return "warning"
        
        else:  # current_state == "healthy"
            # Enter critical if threshold exceeded
            if threshold_critical and value >= threshold_critical:
                return "critical"
            # Enter warning if threshold exceeded
            if threshold_warning and value >= threshold_warning:
                return "warning"
            return "healthy"

    def _generate_alert_message(
        self,
        component_id: str,
        metric_name: str,
        current_value: float,
        threshold_value: float,
        alert_level: AlertLevel
    ) -> str:
        """
        Generate human-readable alert message.
        
        Args:
            component_id: Component identifier
            metric_name: Metric name
            current_value: Current value
            threshold_value: Threshold value
            alert_level: Alert level
            
        Returns:
            Alert message string
        """
        exceedance_pct = ((current_value - threshold_value) / threshold_value * 100) if threshold_value else 0
        
        return (
            f"[{alert_level.upper()}] {component_id} - "
            f"{metric_name} at {current_value:.2f} "
            f"(threshold: {threshold_value:.2f}, +{exceedance_pct:.1f}%)"
        )

    def get_active_alerts(self) -> List[Alert]:
        """Get all currently active alerts."""
        return list(self.active_alerts.values())

    def get_alert_for_component(self, component_id: str) -> Optional[Alert]:
        """Get active alert for a specific component."""
        return self.active_alerts.get(component_id)

    def acknowledge_alert(self, component_id: str) -> bool:
        """
        Mark alert as acknowledged by user.
        
        Args:
            component_id: Component to acknowledge
            
        Returns:
            True if alert was acknowledged, False if no active alert
        """
        if component_id in self.active_alerts:
            self.active_alerts[component_id].acknowledged = True
            logger.info(f"Alert acknowledged for {component_id}")
            return True
        return False

    def get_alert_history(self, limit: int = 100) -> List[Alert]:
        """
        Get alert history.
        
        Args:
            limit: Maximum number of alerts to return
            
        Returns:
            List of recent alerts
        """
        return self.alert_history[-limit:]

    def clear_alert_history(self):
        """Clear alert history."""
        self.alert_history.clear()
        logger.info("Alert history cleared")

    def get_component_status_summary(self) -> Dict[str, Dict]:
        """
        Get summary of all component statuses.
        
        Returns:
            Dict mapping component_id -> {status, alert_if_active}
        """
        summary = {}
        for component_id, alert in self.active_alerts.items():
            summary[component_id] = {
                "status": "alert",
                "level": alert.level.value,
                "metric": alert.metric_name,
                "value": alert.current_value,
                "threshold": alert.threshold_value,
                "message": alert.message
            }
        return summary
